// @ts-nocheck
import popularSalons from '../assets/images/PopularSalons.png';
import stars from '../assets/images/Star.png';

export const upComingData = [
    {
        id: 1,
        salonName: 'Mane Beautilocks',
        date: 'Sat,20 Aug',
        time: '07:00 PM',
        // coverImg: require('../assets/images/UpcomingImage.png'),
        pimg: popularSalons,
        salonAddress: '2/250 Cambridge St,',
        apointmentDate: 'Fri,12 Jun',
        apointmentTime: '2Pm- 3Pm',
        alocateTime: '60 min',
        serviceTitle: 'Total Services',
        serviceCount: '2',
        address: '2/250 Cambridge St, Wembley WA 6014, Australia',
        ratingText: '3.0',
        shopStatus: '85',
        // shopStatus: 'open',
        book: 'Details',
        review: '(21)',
        desti: "1.4 mi",
        stars: stars,
        // image: [
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        // ],
    },
    {
        id: 2,
        salonName: 'Beautilocks',
        date: 'Sat,20 Aug',
        time: '07:00 PM',
        // coverImg: require('../assets/images/UpcomingImage.png'),
        pimg: popularSalons,
        salonAddress: '2/250 Cambridge St,',
        apointmentDate: 'Fri,12 Jun',
        apointmentTime: '2Pm- 3Pm',
        alocateTime: '60 min',
        serviceTitle: 'Total Services',
        address: '2/250 Cambridge St, Wembley WA 6014, Australia',
        serviceCount: '2',
        ratingText: '3.0',
        shopStatus: '96',
        book: 'Details',
        review: '(21)',
        desti: "1.4 mi",
        stars: stars,
        // image: [
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        // ],
    },
    {
        id: 3,
        salonName: 'Mane Beautilocks',
        date: 'Sat,20 Aug',
        time: '07:00 PM',
        // coverImg: require('../assets/images/UpcomingImage.png'),
        pimg: popularSalons,
        salonAddress: '2/250 Cambridge St,',
        apointmentDate: 'Fri,12 Jun',
        address: '2/250 Cambridge St, Wembley WA 6014, Australia',
        apointmentTime: '2Pm- 3Pm',
        alocateTime: '60 min',
        serviceTitle: 'Total Services',
        serviceCount: '2',
        ratingText: '3.0',
        shopStatus: '59',
        book: 'Details',
        review: '(21)',
        desti: "1.4 mi",
        stars: stars,
        // image: [
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        // ],
    },
    {
        id: 4,
        salonName: 'Mane Beautilocks',
        date: 'Sat,20 Aug',
        time: '07:00 PM',
        // coverImg: require('../assets/images/UpcomingImage.png'),
        pimg: popularSalons,
        salonAddress: '2/250 Cambridge St,',
        apointmentDate: 'Fri,12 Jun',
        apointmentTime: '2Pm- 3Pm',
        address: '2/250 Cambridge St, Wembley WA 6014, Australia',
        alocateTime: '60 min',
        serviceTitle: 'Total Services',
        serviceCount: '2',
        ratingText: '3.0',
        shopStatus: '30',
        book: 'Details',
        review: '(21)',
        desti: "1.4 mi",
        stars: stars,
        // image: [
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        // ],
    },
    {
        id: 5,
        salonName: 'Mane Beautilocks',
        date: 'Sat,20 Aug',
        time: '07:00 PM',
        // coverImg: require('../assets/images/UpcomingImage.png'),
        pimg: popularSalons,
        salonAddress: '2/250 Cambridge St,',
        apointmentDate: 'Fri,12 Jun',
        apointmentTime: '2Pm- 3Pm',
        address: '2/250 Cambridge St, Wembley WA 6014, Australia',
        alocateTime: '60 min',
        serviceTitle: 'Total Services',
        serviceCount: '2',
        ratingText: '3.0',
        shopStatus: '77',
        book: 'Details',
        review: '(21)',
        desti: "1.4 mi",
        stars: stars,
        // image: [
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        //     require('../assets/images/UpcomingImage.png'),
        // ],
    },
];

